### ISSUE TITLE
Control logic 

### ISSUE THREAD

**Issue by NikoBach1** [RMUASD-Team1-2017/RMUASD#13]
Test communication between the Control Logic node, and gazebo.
Try takeoff, move to point and land on Gazebo.
Get waypointList to work, for the waypoint navigation

**Comment by ChrelleP** [comment]
We didn't finish with task for the first sprint. The control was more difficult to get up and running than expected. We have put more people on the task and is moving up the priority, since it is a vital link in the whole system.

**Comment by ChrelleP** [comment]
For Sprint 2, we will try to integrate the control logic with ROS so that a single mission can be accepted and completed.

**Comment by ChrelleP** [comment]
Drone logic works and is able to make the drone fly a route
