### ISSUE TITLE
Implement Docking Station

### ISSUE THREAD

**Issue by ChrelleP** [RMUASD-Team1-2017/RMUASD#16]
Implement a dummy docking station node, that mimics the functionality for test purposes.

**Comment by ChrelleP** [comment]
Implemented a small dummy version.

**Comment by loleb** [comment]
Remaining tasks:

- [ ] Source materials

- [ ] Construct mock-up

**Comment by RasmusKS** [comment]
The docking station node does not need to be implemented since the docking station will not be able to open.
