### ISSUE TITLE
Test seriel communication between drone, and PC

### ISSUE THREAD

**Issue by NikoBach2** [RMUASD-Team1-2017/RMUASD#28]
Control the drone using mavros.

**Comment by StefanRvO** [comment]
We should be able to have communication using the GSM and 433 MHz module, and send simple serial commands.

**Comment by VincentTofterup** [comment]
China copy of 3dR 433MHz telemetry module tested yesterday and works at the moment. The Toradex VF61 SOC board was interfaced through the temeletry module. Today the GSM module, U-Blox Sara-G350 was received. A ROS interfacing node received from Kjeld has been tested, however at this moment, no serial data from the module is received. 

The module needs to be run with a battery pluged into it and also an antenna.

**Comment by VincentTofterup** [comment]
current status is that telemetry module is to me connected to flight controller, gsm module to be connected to Toradex VF61 board

**Comment by VincentTofterup** [comment]
Sending/recieving sms messages possible atm. The module is set up as interface on the board. The idea is that instead of using the provided python node, the device is setup as a serial interface. This interface can be used in a socket connection. 

Current status: kernel on vf 61 board is to be compiled with the packages needed for ppp (point ot point protocol) (pppd tool)

**Comment by VincentTofterup** [comment]
The provided ros node for udp messages works one way: it is possible to send packets from the module to the server, not the other way around - that is why ppp is investigated. This enables the module as a serial interfaces which can be setup is a normal socket connection

**Comment by StefanRvO** [comment]
We have sucessfully been able to configure the  GSM module as a ppp interface, making it possible to use normal sockets to connect through the internet. See wiki for setup. Clossing issue.
