### ISSUE TITLE
Improve certainty for control logic

### ISSUE THREAD

**Issue by ChrelleP** [RMUASD-Team1-2017/RMUASD#40]
The control logic checks whether the commands go through to the flight controller, but improvements could be made to make it more robust. E.g. the drone waits for a disarm when it is send on a mission, but if it for some reason does not agree to go on mission (even though it returns success on the mode change) it will disarm by itself and the drone thinks it is done with the mission...

**Comment by NikoBach2** [comment]
Is fixed, so the drone checks if it is in the air, before it returns on mission. If the drone is not in the air after 10 seconds, it goes to fail state. 
Arming is fixed too.
