### ISSUE TITLE
Trigger aborts on OES in appropriate scenarios

### ISSUE THREAD

**Issue by ChrelleP** [RMUASD-Team1-2017/RMUASD#47]
Look into implementing the correct aborts on the OES, based on the scenarios described in the SORA failure scenrio segment. Examples are failure of GPS's, no connection to GCS or other.

**Comment by StefanRvO** [comment]
The OES have to trigger an abort on the following conditions:
* GSM is lost, and the telemetry link is lost too.
* GCS communication loss is detected, but the internet connection is still available.

Internet availability is detected by pinging googles DNS servers.

**Comment by StefanRvO** [comment]
fc1d2f00f875e7d3ccbf33f21fb01672092d58ee and c986fe85ea652a7a3cc49b856386961626a7a98e implements this.
