### ISSUE TITLE
Heartbeat from GSM

### ISSUE THREAD

**Issue by ChrelleP** [RMUASD-Team1-2017/RMUASD#51]
Currently the GSM module will send a GPS signal that could be used for heartbeat, but if the GPS signal is lost, it will stop sending. Thus we need to have another kind of heartbeat to monitor, so we don't think the link is lost when its just the GPS.

**Comment by StefanRvO** [comment]
The onboard software now publishes a heartbeat every 1 second through rabbitmq, So closing the issue.
We still need to added the topic to the rabbitMQ bridge. This is resolved in 1143383
