### ISSUE TITLE
Testing of the whole system

### ISSUE THREAD

**Issue by ChrelleP** [RMUASD-Team1-2017/RMUASD#54]
We should get as many testing hours as possible, preferably using the whole system with app and so on.

**Comment by VincentTofterup** [comment]
Test today monday 13/11. We ran into geofence violation when the drone flew further than the inbuilt 50 meter radius maximum. This has been altered to fit the model airfield. The alternative is to turn it completely off or set it to the largest distance to a rallypoint/pathplanning point.

**Comment by ChrelleP** [comment]
Closing since we can see stuff works, now we just need to verify and get flight hours for every part of the system.
