### ISSUE TITLE
Risk Assessment Node

### ISSUE THREAD

**Issue by loleb** [RMUASD-Team1-2017/RMUASD#55]
- [x] Decide on the use of metrics in allowing flight
- [x] Decide on the weighting of metrics
- [x] Decide whether or not to keep factors pertaining to 'other obstacles' and 'number of golfers', etc., if we cannot accurately determine them.

**Comment by loleb** [comment]
These factors are not necessary for a current implementation. 'other obstacles' and 'number of golfers' are implemented, but have no influence on the metric (set to zero), so proceed just looking at wind and rain conditions.

This should be linked with the mission planner node, etc.

**Comment by NikoBach2** [comment]
Are started making the connection between the risk assement node, and the health check node. 
This will be doen, so the mission handler node does not have connection to the health check node, but only the risk assesment node.
