### ISSUE TITLE
Edit the load landing spot node in order to load the rallypoint file from QGroundControl.

### ISSUE THREAD

**Issue by RasmusKS** [RMUASD-Team1-2017/RMUASD#58]
Change the loadLandingspot function in the path_planner in order to load the rally points file extracted from QGroundControl.
JSON lib: https://github.com/nlohmann/json

**Comment by VincentTofterup** [comment]
Rallypoint file from QGroundControl loaded into software and saved as safe landing sites, ensuring easy UI. Finished issue.
