### ISSUE TITLE
[OES/GCS] Create battery failsafe

### ISSUE THREAD

**Issue by StefanRvO** [RMUASD-Team1-2017/RMUASD#72]
Detect battery voltage, and change to LAND mode if below a certain voltage. (The PX4 can/does already do this. Maybe we should discuss if we also need to this in our system)

**Comment by StefanRvO** [comment]
ecdd42f41c812588c684c4ba6d5fdf410664c44d implements this on the drone. We change to LAND mode if battery voltage get below 3500 mV * BATTERY_CELLS

**Comment by StefanRvO** [comment]
We currently have battery monitoring safety on the OES, which performs a landing if the battery is below 3500 mV * BATTERY_CELLS (10.5V for 3 cells) as well as a battery preflight check, which will not perform a mission if the battery is below 11.5V. Closing issue

**Comment by StefanRvO** [comment]
Not completly done on GCS

**Comment by NikoBach2** [comment]
Battery failsafe is implemented on the GCS.
