### ISSUE TITLE
Find out why GPS does not get fix

### ISSUE THREAD

**Issue by ChrelleP** [RMUASD-Team1-2017/RMUASD#76]
For some reason we can't get GPS fix from the GPS, so we need to test and see what might be the cause. We can potentially get the other group's GPS to see if it is a problem with our GPS or the pixhawk.

**Comment by VincentTofterup** [comment]
We have been debugging this matter more in depth. We do get a fix, but not a very good one. The steps that needs to be taken is to make a ground plane for the GPS to sit on top on, and furthermore a mounting that raises the module 10-15 centimeters.

**Comment by ChrelleP** [comment]
The GPS seems to just get really bad signals, since after making a ground plane we could see improvements, and actually get the old GPS that didn't work, to get a fix. So we are closing it for now and focusing on getting the new GPS higher up and with a ground plane.
