### ISSUE TITLE
Create and solder a ground plane for Here+ GPS

### ISSUE THREAD

**Issue by VincentTofterup** [RMUASD-Team1-2017/RMUASD#85]
Create and solder a ground plane like the one on this guide;

http://autoquad.org/wiki/wiki/configuring-autoquad-flightcontroller/gps-groundplane/

This would lead to the following subtasks:
- [x] Take module apart to get to antenna aluminum casing
- [x] Cut and solder copper plates together
- [x] Attach module to plane and figure out how to attach on top of Flight Controller 
- [x] Figure out if horizontal placement is needed when this is made
- [x] Test potential increase in performance 

Edit: Ground plane does not have to be exactly like the one in the link. But, in terms of GPS signal reflection and overall reflector antenna theory it would make sense to pursue.

**Comment by ChrelleP** [comment]
We tested with a temporary simple ground plane, which made good improvements to the old GPS. Now Louis have made a better stand + ground plane that we need to solder to the current and better GPS, so we get a consistent signal.

**Comment by RasmusKS** [comment]
The ground plane is done but due to broken 3d print the gps is not mounted jet.

**Comment by ChrelleP** [comment]
We got good GPS signal so it seems to work.
